# Generated by Django 4.1.7 on 2023-05-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maild_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Business Mail')),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone No')),
                ('country_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Country Code')),
                ('business_address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='kenzie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Platform')),
                ('icon_class', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon Class')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
