# Generated by Django 4.1.7 on 2023-03-04 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=3, verbose_name='Rating')),
                ('content', models.TextField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
