# Generated by Django 4.1.7 on 2023-03-04 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
