# Generated by Django 4.1.7 on 2023-03-04 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_membership_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='Bill',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.bill'),
        ),
    ]
