# Generated by Django 4.1.7 on 2023-03-06 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0006_category_product'),
        ('customer', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appadmin.package'),
        ),
    ]
