# Generated by Django 4.1.7 on 2023-03-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_cart_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
