# Generated by Django 4.1.7 on 2023-03-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Price',
            field=models.FloatField(default=0),
        ),
    ]
