# Generated by Django 4.1.7 on 2023-03-10 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0010_delete_product_review'),
        ('accounts', '0004_customuser_profile_image'),
        ('customer', '0011_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_of_review', models.IntegerField(verbose_name='No of Review')),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Review', to='appadmin.product')),
                ('user', models.ManyToManyField(blank=True, null=True, to='accounts.customer_details')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField(verbose_name='Comment')),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='appadmin.product')),
                ('user', models.ManyToManyField(blank=True, null=True, to='accounts.customer_details')),
            ],
        ),
    ]
