# Generated by Django 4.1.7 on 2023-02-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_trainer_details_facebook_trainer_details_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_image/', verbose_name='Profile Image'),
        ),
    ]
