# Generated by Django 4.1.7 on 2023-02-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Platform')),
                ('Content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='Title')),
                ('photos', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maild_id', models.CharField(max_length=50, verbose_name='Business Mail')),
                ('phone_no', models.CharField(max_length=10, verbose_name='Phone No')),
                ('country_code', models.CharField(max_length=5, verbose_name='Country Code')),
                ('business_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='social_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Platform')),
                ('icon_class', models.CharField(max_length=50, verbose_name='Icon Class')),
                ('url', models.URLField()),
            ],
        ),
    ]
