# Generated by Django 4.1.7 on 2023-02-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='headline_cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Name')),
                ('short_description', models.CharField(max_length=250, verbose_name='Name')),
                ('Content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='cards',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
