# Generated by Django 4.1.7 on 2023-02-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_headline_cards_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='Content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cards',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='Title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='headline_cards',
            name='Content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='headline_cards',
            name='Name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='headline_cards',
            name='short_description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='information',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='information',
            name='maild_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Business Mail'),
        ),
        migrations.AlterField(
            model_name='information',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone No'),
        ),
        migrations.AlterField(
            model_name='social_info',
            name='icon_class',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon Class'),
        ),
        migrations.AlterField(
            model_name='social_info',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='social_info',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
