# Generated by Django 4.1.7 on 2023-03-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_cards_content_alter_cards_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150, verbose_name='Name')),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.CharField(max_length=10)),
                ('Message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
