# Generated by Django 4.1.7 on 2023-02-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0002_package_duration_alter_package_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='Message',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Commitment Message'),
        ),
    ]
