# Generated by Django 4.1.7 on 2023-03-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0003_package_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='theme',
            field=models.CharField(choices=[('Black', 'Black'), ('white', 'White')], max_length=20, null=True),
        ),
    ]
