# Generated by Django 4.1.7 on 2023-03-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0004_package_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='Name')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('Address', models.TextField(verbose_name='Address')),
                ('Recent', models.CharField(max_length=500, verbose_name='Recent Experience')),
                ('Past', models.CharField(max_length=500, verbose_name='Past Experience')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='instagram')),
                ('cv', models.FileField(upload_to='', verbose_name='CV')),
            ],
        ),
    ]
