# Generated by Django 4.1.7 on 2023-03-06 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0005_job_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=200, unique=True, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_id', models.CharField(max_length=100, unique=True, verbose_name='Product Id')),
                ('Product_Name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('Quantity', models.IntegerField(verbose_name='Quantity')),
                ('Price', models.FloatField(verbose_name='Price')),
                ('Product_Description', models.TextField(blank=True, null=True, verbose_name='Product Description')),
                ('Product_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appadmin.category', verbose_name='Product Category')),
            ],
        ),
    ]
