# Generated by Django 4.1.7 on 2023-03-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0008_job_request_profile_pic_alter_job_request_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_request',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/job_request/profilepic/'),
        ),
        migrations.CreateModel(
            name='Product_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_of_review', models.IntegerField()),
                ('Product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Review', to='appadmin.product')),
            ],
        ),
    ]
