# Generated by Django 4.1.7 on 2023-03-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0009_alter_job_request_profile_pic_product_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_Review',
        ),
    ]
