# Generated by Django 4.1.7 on 2023-03-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0010_delete_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Droping_Price',
            field=models.FloatField(default=240, verbose_name='Droping Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.FloatField(blank=True, null=True, verbose_name='Price'),
        ),
    ]
