# Generated by Django 4.1.7 on 2023-03-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0011_product_droping_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Avg_Review',
            field=models.IntegerField(default=0, verbose_name='Average Review'),
        ),
    ]
