# Generated by Django 4.1.7 on 2023-03-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadmin', '0013_product_product_tag_1_product_product_tag_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/'),
        ),
    ]
